### ISSUE TITLE
Interessados em ajudar

### ISSUE THREAD

**Issue by mathiasgrimm** [phpEmpregos/phpEmpregos.com#1]
Adicione seu nome na lista

**Comment by miltonviziak** [comment]
Milton Cesar Viziak

**Comment by mathiasgrimm** [comment]
vc precisa dar um fork no projeto e enviar um pull request

**Comment by miltonviziak** [comment]
E agora ?

**Comment by YanMagale** [comment]
Yan Magalhães

**Comment by YanMagale** [comment]
Agora é so aguardar que ele vai aceitar o pull request :D

**Comment by miltonviziak** [comment]
ok
