### ISSUE TITLE
Parabéns pelo projeto e sugestoes

### ISSUE THREAD

**Issue by InFog** [phpEmpregos/phpEmpregos.com#16]
Olá!

Em primeiro lugar, parabéns pelo projeto e pela coragem de abrir mao de todas as decisoes para tornar o desenvolvimento aberto e comunitário.

Nao será um caminho fácil, pois comunidade tem sempre seus altos e baixos e nem sempre a colaboracao vai realmente acontecer. Entao, forca e paciencia :)

Eu acho, de verdade, que tem tudo a ver fazer um projeto aberto para um site desse tipo, afinal, a comunidade PHP é a mais interessada no assunto.

Eu gostaria de dar algumas dicas para ajudar no caminho. Essas dicas sao baseadas em minhas experiencias com open source e com comunidades e sao, basicamente, a minha opiniao, que, nao necessariamente, sao a verdade absoluta sobre o assunto ;)

Vamos lá:

- Nao deixe todas as decisoes na mao da comunidade. Se quiser adotar alguma tecnologia ou fazer alguma mudanca, das duas uma: abra uma votacao com data para terminar ou simplesmente faca e mande o pull request. As vezes, querer perguntar se algo deve ou nao ser feito e quem apoia, etc, pode demorar muito e desmotivar.

- Peca ajuda sempre que possível e delegue funcoes. Algo como um responsável por aprovar os PR de UI, outro os PR de backend, outro os relacionados à qualidade de código, etc. Isso vai ajudar bastante, mas é algo que pode surgir naturalmente na comunidade.

Agora, principal, na minha opiniao. Acho que voce deveria ter comecado colocando o código, abrindo algumas issues e chamando a comunidade para ajudar. Pedir para as pessoas colocarem seus nomes no readme como colaboradores é uma tarefa simples, agora, esperar que elas realmente colaborem no futuro, é mais complicado. O GitHub (ou outras ferramentas Git) vai mostrar os colaboradores. Entao, publique o código, defina algumas metas, chame as pessoas para realmente comecar a colaborar e, importante, mantenha as expectativas baixas, pois assim, qualquer colaboracao será realmente muito lucrativa :)

Boa sorte com o projeto, boa sorte para a comunidade e sucesso para todos.

**Comment by mathiasgrimm** [comment]
Blz! value pelas dicas! Com certeza vão ser úteis.

O código será submetido em breve e assim teremos algo mais real para conversar.

A princípio o que já poderia ser feita seria criar uma identidade visual para o site. Vou criar um issue agora mesmo.

**Comment by YanMagale** [comment]
Muito boa a sugestão do @InFog. Acho que poderíamos ir criando as issues das primeiras coisas que precisam ser feitas... 

Acredito que esse controle dos PR de UI e de back-end seja criado ao longo do tempo de forma natural, de acordo com a quantidade de PR e do tamanho do projeto.

**Comment by mathiasgrimm** [comment]
Exatamente

Que comecem os git issues!

**Comment by lerox** [comment]
@InFog +1
