### ISSUE TITLE
Cria e definir License

### ISSUE THREAD

**Issue by mathiasgrimm** [phpEmpregos/phpEmpregos.com#26]
arquivo ja existe, precisa adicionar conteudo

**Comment by miltonviziak** [comment]
se você pretende deixar o software livre e ter essas liberdades:
Liberdade 0: A liberdade de executar o programa, para qualquer propósito.
Liberdade 1: A liberdade de estudar como o programa funciona, e adaptá-lo para as suas necessidades. Acesso ao código-fonte é um pré-requisito para esta liberdade.
Liberdade 2: A liberdade de redistribuir cópias de modo que você possa ajudar ao seu próximo.
Liberdade 3: A liberdade de aperfeiçoar o programa, e redistribuir seus aperfeiçoamentos, de modo que toda a comunidade possa se beneficiar.

o que acham da license apache ?

**Comment by mathiasgrimm** [comment]
Qual as diferencas dela da MIT e BSD? resumidamente

**Comment by miltonviziak** [comment]
Quase nenhuma as tres permitem obtenção e modificação do codigo fonte.
A BSD impõe uma restrição que é para manter os créditos do auto original.
A do MIT pede para manter o aviso de copyright.
A do Apache diz que todo contribuidor do código também concede uma license mundial para o uso de sua contribuição.

**Comment by mathiasgrimm** [comment]
qualquer uma est'a bem para mim. A MIT acho legal

**Comment by miltonviziak** [comment]
posso modificar o arquivo license com o texto do MIT então ?

**Comment by mathiasgrimm** [comment]
pode!

**Comment by miltonviziak** [comment]
mas só uma duvida,  as 3 podem ser comercializadas por quem quiser não tem nenhum problema ?

**Comment by mathiasgrimm** [comment]
acredito que é tranquilo

**Comment by miltonviziak** [comment]
blz

**Comment by mathiasgrimm** [comment]
resolvido!
Valeu @miltonviziak
