### ISSUE TITLE
portugues/ingles

### ISSUE THREAD

**Issue by mathiasgrimm** [phpEmpregos/phpEmpregos.com#34]
vamos definir o banco de dados  utilizando portugues ou ingles?

Estava pensando em fazer tudo em ingles, que eh a maneira que o atual é.

As exceções seriam para palavras de semântica relevante, como por exemplo CPF, RG, CNPJ etc...
embora não tenha nenhum caso desses no site atual.

**Comment by miltonviziak** [comment]
pode ser ingles

**Comment by mathiasgrimm** [comment]
tb acho

**Comment by luizreginaldo** [comment]
também sou a favor do inglês

**Comment by YanMagale** [comment]
Por mim tb pode, mas nao tenho nada contra caso adotem o português.

**Comment by dtgfranca** [comment]
Também acredito que o inglês é uma boa , com exceção de algumas palavras como foi dito pelo mathias

**Comment by dunice** [comment]
Acredito que o projeto deveria adotar inglês tanto no banco de dados quanto no código, justamente para manter consistência do código/aplicação, excluindo os campos que você mencionou. E trabalhar com arquivos de internacionalização i18n.

**Comment by vinicius-ianni** [comment]
Se vai usar inglês como padrão, campos que vão armazenar dados como documentos (específicos para cada pais) devem estar numa tabela em separado com campos somente texto e o tratamento/formatação desses dados ocorrendo em js/php ou algo assim.
Assim, mantêm-se um padrão no banco de dados que não precisará de alterações em sua estrutura e eventuais alterações seriam feitas num arquivo próprio, como sendo um plugin ou algo do tipo.

**Comment by mathiasgrimm** [comment]
hum, acredito que nesse caso a complexidade aumentaria bastante.

Tem algum projeto utilizando essa proposta?

**Comment by mathiasgrimm** [comment]
fechou ingles então.

Para campos específicos tipo cpf, cnpj e outros do tipo, os nomes permanecerão em português.
