### ISSUE TITLE
Olá pessoal!

### ISSUE THREAD

**Issue by Jessica7** [phpEmpregos/phpEmpregos.com#36]
Olá fiquei interessada em ajudar! espero, contribuir e aprender tbm junto com vocês :)

**Comment by mathiasgrimm** [comment]
Ótimo, acho q vc é a primeira mulher que se juntou a nós!
seja bem-vinda!

se atraca nos git issues!

tem alguma ideia de como poderia ajudar?

**Comment by Jessica7** [comment]
Muitíssimo obrigada Mathias!  em 2013 desenvolvi meu primeiro sistema com PHP/MySQL e atualmente venho  estudando: JavaScript ,AngularJS, CSS, HTML e há algumas semanas NodeJS. Então posso ajudar nas tecnologias citadas acima e algumas ideias para o site. Será uma honra participar desse projeto. Mathias o grupo possui algum email / Slack ?

**Comment by mathiasgrimm** [comment]
sim, #phpempregos no freenode IRC

**Comment by mathiasgrimm** [comment]
Com relação a ajudar, vejo que front end é sua praia.

Precisamos muito melhorar o front end. Não sei nem por onde começar. Vou deixar para os entendidos decidirem

Da uma olhada no https://phpEmpregos.com pra ter uma idéia do atual

**Comment by YanMagale** [comment]
Com relação ao novo layout, não sei qual é a intenção inicial, mas talvez seja interesse colher a opiniao de algum designer para dar uma sugestão no layout e etc...

Em todo caso, é possível criar um markup rápido no link https://webflow.com/

**Comment by mathiasgrimm** [comment]
Legal.

A idéia ainda não sei.
Eu acho que deveria seguir o estilo clean e simplista mas minha especialidade passa longe do front end!

**Comment by mathiasgrimm** [comment]
Precisamos juntar o pessoal do front end pra decidir alguma coisa
