### ISSUE TITLE
Ambiente de desenvolvimento (vagrant)

### ISSUE THREAD

**Issue by gustavoper** [phpEmpregos/phpEmpregos.com#39]
Seria interessante se tivessemos um ambiente único e pré-configurado de desenvolvimento, para reproduzir com maior fidelidade possível o ambiente de produção.

O que vem na minha cabeça é um script do vagrant + ansible, a ser inserido no branch de desenvolvimento.

**Comment by mathiasgrimm** [comment]
exato
e se chama homestead :)

laravel.com/docs/5.0/homestead

**Comment by gustavoper** [comment]
Beleza, só seria interessante então colocar no README =)

**Comment by mathiasgrimm** [comment]
Os dados do banco de dados de produção não serão de acesso ao público e somente o core team terá acesso, caso necessário. N existe um core team ainda :) será formado com o tempo, naturalmente

Para desenvolver utilizaremos seeders (http://laravel.com/docs/5.0/migrations) juntamente com Fakers (https://github.com/fzaninotto/Faker) o que será suficiente para podermos desenvolver tranquilamente.

O banco de dados de produção não poderá ser divulgado por questões de privacidade dos dados dos usuários/empresas como email, vagas no aplicou etc... isso seria de muitas formas constrangedor

**Comment by mathiasgrimm** [comment]
vou atualizar o readme. Valeu! boa idéia

**Comment by vicainelli** [comment]
Se é OpenSource, não vejo o motivo de apenas uma pessoa ter acesso aos dados dos usuários.
Isso tá ficando bem restrito pelo que estou vendo.

**Comment by mathiasgrimm** [comment]
O google eh open source mas nem por isso temos acesso aos emails de todas as pessoas.

Como falei, certas pessoas terão acesso. O core team será formado e ele terá acesso quando necessário.

Tem empresas que não querem divulgar seus nomes e também candidatos que não gostariam de mostrar que estão se candidatando.

Acredito que nenhum site/projeto open source deixa disponível a informações dos usuários.

**Comment by mathiasgrimm** [comment]
O banco de dados de produção não é importante. 
Podemos fazer um dump e alterar dados sensíveis mas nem acho que seja necessário.

Seeders funcionam muito bem

**Comment by mathiasgrimm** [comment]
o github mesmo eh open source. podemos farkar o projeto, mas duvido que teremos acesso ao um unico email.

**Comment by mathiasgrimm** [comment]
Meu único interesse é proteger a privacidade dos usuários/empresas.

**Comment by vicainelli** [comment]
Sinceramente, não estou vendo um trabalho em conjunto.
E sim alguém que já definiu tudo e está ditanto as regras de como quer que o trabalho seja feito.

Desculpa, mas é a ideia que está me passando com todas essas regras.

**Comment by mathiasgrimm** [comment]
Desculpa mas realmente não é essa a idéia.
Preciso que as pessoas fiquem engajadas no projeto e assim começo a distribuir a responsabilidade.

A parte do front-end por exemplo precisa de um líder. 

Mas a migração de algo proprietário para algo open source é delicada.
Esse projeto foi sempre um projeto particular, desde 2009. Agora foi aberto ao público e todos estão convidados a ajudar.

Tenho a experiência de 6 anos com o site, o que certamente outras pessoas não tem.

Não posso simplesmente pegar o banco de dados e disponibilizar o dump.

**Comment by mathiasgrimm** [comment]
Não está vendo um trabalho conjunto? temos 20 issues onde já podemos trabalhar. Idéias já estão sendo fomentadas mas até agora ninguém tomou a frente de nada, o que é natural.

Algumas coisas vou ter q migrar manualmente do código fonte antigo pro novo e a parte do backend vai ter um inicio menos rápido que outras áreas do site, mas gradualmente tudo será feito de maneira colaborativa e atingira um nirvana colaborativo.

Até o momento as pessoas não tem muito o que trabalhar, preciso disponibilizar mais código e assim mais pessoas ficarão envolvidas. Mas preciso pessoas que assumam algumas áreas.

Até o momento, o banco de dados não será disponibilizado. Isso é algo que traremos a discussão novamente. Mas devemos avaliar como são feitos em outros projetos open source e pedir a opinião de pessoas mais experientes.

Eu, nas minhas limitações técnicas e faculdades mentais, venho servir apenas de instrumentalizador para uma necessidade da comunidade. Não tenho todo conhecimento e nem sou quem tem as melhores decisões. Será uma caminhada de aprendizado para mim e para muitos outros que se envolverão no projeto.  Espero fazer o melhor mas com certeza não acertarei em todas decisões. 

Tornar esse projeto open source acredito que tenha sido um bom passo na direção da sanidade.

**Comment by gustavoper** [comment]
+ 1 @mathiasgrimm, realmente o dump completo (tabelas + dados) do banco de produção atual não vai ajudar muito. Até porque com certeza, hoje tem informação que o usuário (empresa e/ou candidato) não permite disponibilizar publicamente.

Apenas disponibilize a estrutura de tabelas, ou o script do migration já pronto para que o pessoal possa começar a implementar algo. Já tá de bom tamanho.

Daí aos poucos o projeto vai tomando forma. Vamo que vamo!

Forte abraço!

(PS: Como você mesmo já colocou no README, acredito que já pode fechar a issue).
