### ISSUE TITLE
Usar framework ?

### ISSUE THREAD

**Issue by miltonviziak** [phpEmpregos/phpEmpregos.com#43]
Uma duvida compensa usar framework ou fazer tudo na mão ?

**Comment by mathiasgrimm** [comment]
Poderia ser feito com o bom e velho php mas nesse caso utilizaremos Laravel 5.
É uma grande oportunidade de aprender um framework

O fato de utilizar um framework é pois no meu dia a dia já utilizo laravel e com ele sou mais produtivo.
Dessa maneira também facilita disponibilizar documentação para qualquer outra pessoa pois o framework já tem documentação e várias fontes de estudos que incluem video aulas, livros, artigos etc.

**Comment by miltonviziak** [comment]
é que fazer um site com php puro eu sei.estou estudando agora orientação a objetos

**Comment by miltonviziak** [comment]
ja instalei o laravel to dando uma olhada na documentação

**Comment by mathiasgrimm** [comment]
Legal, da uma estudada.

Hoje em dia é necessário saber algum framework, a maioria das empresas utilizam algum

**Comment by miltonviziak** [comment]
ok

**Comment by mathiasgrimm** [comment]
mesmo que vc não tenha experiência, é bem vindo

**Comment by edertaveira** [comment]
Uma sugestão de arquitetura muito util que uso inclusive em alguns projetos
que deram muito certo é:
AngularJS, Slim Framework e Doctrine (Ou outro framework de persistência).

Pelo escopo do projeto que tenho em mente, não é algo muito grande, então
ao meu ver o Slim resolve a parada, e ele acoplado ao Angular é uma mão na
roda no desenvolvimento. Ele seria nossa API que se comunicaria com uma
classe de Resource e esta por vez com a parte de persistência.

Porém estou aberto a outras tecnologias, foi somente uma sugestão. :)

Em qui, 12 de mar de 2015 às 08:23, Mathias Grimm <notifications@github.com>
escreveu:

**Comment by mathiasgrimm** [comment]
vou criar uma thread soh pra discutir a tecnologia.
A principio estou utilizando Laravel q eh bem simples

Framework é apenas um meio e não um fim.
Essa discussão de framework eh sem fim mas acredito que vou criar uma issue pra isso
