### ISSUE TITLE
Criar arquivo de contribuição (CONTRIBUTING)

### ISSUE THREAD

**Issue by leocavalcante** [phpEmpregos/phpEmpregos.com#45]
Os commits serão em português ou inglês? Tem que enviar PR com testes? Faço direto no master?
https://github.com/blog/1184-contributing-guidelines

**Comment by mathiasgrimm** [comment]
os commits em ingles se possivel
o ideal eh sempre vc criar um branch com a feature tipo feature_nova_pagina e mandar o PR pro master

**Comment by leocavalcante** [comment]
Então, cria um arquivo chamado CONTRIBUTING, pode ser em Markdown e coloca na raiz do projeto dizendo sobre essas especificações (vide link).

**Comment by mathiasgrimm** [comment]
Blz!

Ta afim de criar?

**Comment by leocavalcante** [comment]
Pode ser, quais são as guidelines pra contribuir no projeto?
(Só acho que se for pra você listar aqui, mais fácil você listar no arquivo direto, já que eu só daria um Ctrl+C/Ctrl+V, mas tudo bem...)

**Comment by mathiasgrimm** [comment]
Cria uma versao que vc acha legal e a gente vai melhorando.

**Comment by leocavalcante** [comment]
Beleza.
