### ISSUE TITLE
Integração contínua (CI)

### ISSUE THREAD

**Issue by leocavalcante** [phpEmpregos/phpEmpregos.com#46]
Adicionar o projeto num servidor de Integração Contínua automatizada.
Sugestão: https://travis-ci.org

**Comment by mathiasgrimm** [comment]
legal, vou criar.
Alguma coisa que preciso saber antes de criar?

**Comment by mathiasgrimm** [comment]
nunca usei o trevis

**Comment by leocavalcante** [comment]
É bem simples e o projeto já tá configurado pro phpunit, então vai ser bem tranquilo:
http://docs.travis-ci.com/user/languages/php/

**Comment by mathiasgrimm** [comment]
legal, vou configurar !

**Comment by mathiasgrimm** [comment]
https://travis-ci.org/profile/phpEmpregos

**Comment by mathiasgrimm** [comment]
whats next?

**Comment by mathiasgrimm** [comment]
criei o .travis.yml já

**Comment by leocavalcante** [comment]
Boa!

**Comment by dunice** [comment]
@mathiasgrimm cria também pra sdk-php.

**Comment by mathiasgrimm** [comment]
crido na verdade

**Comment by mathiasgrimm** [comment]
criado*
