### ISSUE TITLE
Migration/Seed da tabela Job

### ISSUE THREAD

**Issue by mathiasgrimm** [phpEmpregos/phpEmpregos.com#52]
Criei a migration e o seeder da tabela job. ja da pra come'car a brincar agora.

php artisan migrate
php artisan db:seed

**Comment by miltonviziak** [comment]
seria isso @mathiasgrimm :
    Schema::create('job', function($table)
    {
      $table->serial('id');
      $table->char('title');
      $table->char('location');
      $table->text('description');
      $table->char('status');
      $table->string('email');
      $table->string('email_subject_prefix');
      $table->char('advertiser_name');
      $table->char('advertiser_url');
      $table->string('contact_email');
      $table->text('question_1');
      $table->char('question_2');
      $table->char('question_3');
      $table->char('external_id');
      $table->nullableTimestamps('published_at');
      $table->nullableTimestamps('updated_at');
      $table->timestamps('created_at');
      $table->increments('job_id_pk');
      $table->integer('job_external_id_uk')->unique();
      $table->enum('job_status_ck', ['DRAFT','PENDING','PUBLISHED','REJECTED','FILLED'])->unique();
    });

**Comment by rodolfobandeira** [comment]
@miltonviziak isso ja foi feito. Veja no meu ultimo pull request

**Comment by miltonviziak** [comment]
a tah.é que ainda não deu merge né.

**Comment by mathiasgrimm** [comment]
acabei de dar um merge @miltonviziak. Deu um merge no pr do @rodolfobandeira e alterei algumas coisa.

@rodolfobandeira provavelmente vc vai ter q dar um rollback nas suas migrations e rodar novamente

**Comment by rodolfobandeira** [comment]
blz @mathiasgrimm :+1:
