### ISSUE TITLE
Postgres vs MySQL?

### ISSUE THREAD

**Issue by mathiasgrimm** [phpEmpregos/phpEmpregos.com#53]
Que comecem os jogos!

Eu gosto mais do Postgres mas acho que a instalacao dele 'e mais complicada e tem menos ferramentas no mercado, o que pode atrapalhar um pouco no engajamento dos poss'iveis desenvolvedores.

O MySQL se usado com sql_mode=TRADITIONAL 'e muito bom e provavelmente todo desenvolvedor ja esta habituado com mysql.

Estamos na fase inicial do projeto, o banco s'o tem 1 tabela e ainda podemos considerar essa alteracao

Eu gosto muito de utilizar o HeidiSQL http://www.heidisql.com/ (mesmo no mac utilizado ele emulado com wine) e acho o pgAdmin3 muito prec'ario

O MySQL acabou de lan'car a vers~ao 5.7 que talvez seja uma coisa a mais em favor do mysql.

Realmente minha maior preocupacao 'e no sentido de facilitar ao maximo a participacao de outras pessoas no projeto, e ao mesmo tempo dar uma oportunidade de aprendermos algo novo.

Meu cora'cao est'a divid'ido :)

**Comment by edertaveira** [comment]
Acredito que o MySQL atende muito bem neste projeto.

Em sex, 13 de mar de 2015 às 09:27, Mathias Grimm <notifications@github.com>
escreveu:

**Comment by luizreginaldo** [comment]
Também sou a favor do MySQL/MariaDB

**Comment by dunice** [comment]
Você tocou num ponto fraco em do PostgreSQL... ferramentas free disponíveis (que sejam boas), principalmente relativa a modelagem. 

Como não conheço as ferramentas do MySQL para o MariaDB, me abstenho.

Por conta disso, eu voto no MySQL.

**Comment by mathiasgrimm** [comment]
MySQL tem varias variacos tipo percona, mariadb etc... mas acho q se fosse optar pelo mysql, seria o mysql da oracle mesmo

**Comment by edertaveira** [comment]
O MySQL tem o Mysql Worckbench que é free e tem inclusive ferramente
interna de modelagem. Costumo trabalhar com ele em projetos que usam MySQL
 e me atende 100%.

Em sex, 13 de mar de 2015 às 10:44, Mathias Grimm <notifications@github.com>
escreveu:

**Comment by mathiasgrimm** [comment]
Alguns dos meus maiores problemas foram resolvidos na versao 5.7
agora o modo strict eh default por padrao...

**Comment by leocavalcante** [comment]
MySQL 5.6+

**Comment by dtgfranca** [comment]
Também voto no MYSQL por ser o banco que utilizo no meu dia a dia .

**Comment by miltonviziak** [comment]
Também voto no mysql

**Comment by mathiasgrimm** [comment]
alguem ja utilizou postgres ou ja utilizou mysql com sql_mode=TRADITIONAL?

**Comment by miltonviziak** [comment]
eu não

**Comment by vanildosouto** [comment]
A pouca experiência que tive com o postgres foi para configurá-lo no Jira, e realmente é bem chatinho criar usuário, banco de dados, configurar...
Acredito que o Mysql seja uma opção melhor, pela facilidade  tanto no uso, quanto a informações disponiveis na internet.

**Comment by mathiasgrimm** [comment]
:)

Alguem mais? fale agora ou cale-se para sempre!

**Comment by vinicius-ianni** [comment]
Bom, a questão ao meu ver, tem duas formas de abordagem:
A primeira é a facilidade de uso/conhecimento que os participantes do projeto possuem.
Nesse aspecto, nem é preciso perguntar, pois o mysql ganha disparado, seja por ser mais fácil para quem esta iniciando encontrar tutoriais de como usar php com mysql, seja por pacotes como o wamp/lamp
Além disso, muitos, senão todos, já instalaram o wordpress/joomla em algum momento seja para fazer o próprio site, seja para customizar algo.

A outra abordagem seria a questão do aprendizado, nesse caso, usar o postgresql neste projeto será para muitos a primeira vez (minha inclusive) que terão contato com o mesmo.

Questões como ferramentas/interfaces, cada um tem as suas, e é obvio que quanto mais popular algo, mais opções ele terá.

Neste ponto, a pergunta que fica mais evidente seria ao meu ver: prosseguir como um projeto de criação de uma plataforma/ferramenta que possa ser utilizada facilmente por qualquer um em qualquer hospedagem (encontra-se muito mais facilmente hospedagens com mysql como db padrão) ou seguir com um projeto que também tenha um objetivo educacional ensinando o uso de um outro banco de dados que apesar de também ser consolidado no mercado não é tão comum seu uso ao menos na nossa realidade nacional ?

**Comment by mathiasgrimm** [comment]
entao @vinicius-ianni, boa abordagem a sua.

Acredito que consigamos combinar todas opções nesse projeto.
Vai rolar um aprendizado já em relação ao framework e com relação ao próprio mysql pois utilizaremos sql_mode=traditional o que vai ser uma grande diferença para muitos.

Futuramente podemos fazer o site compatibel tanto com mysql e postgres. n eh muito complicado, principamente por causa das migrations que usam uma linguagem genérica

**Comment by mathiasgrimm** [comment]
Ok pessoal, pelo que parece o MySQL ta ganhando a briga.

o @rodolfobandeira ta preparando as migrations pra mysql, deve mandar o PR em breve

**Comment by rodolfobandeira** [comment]
Na verdade agora com migrations cada um usa o que quiser. Se for usar PostgreeSql é só editar o config/database.php. (Só deixem o arquivo modificado no repo logal para nao virar bagunça)

Eu vou usar MySQL. Já que você pretende rodar no Amazon AWS, poderemos no futuro migrar o DB para o Amazon RDS.

Abraço!

**Comment by leocavalcante** [comment]
Não vai dar pra cada um usar o que quiser exatamente.
O Eloquent abstrai conexão, não query e tem queries que não são suportadas nos dois bancos.
Se o projeto se manter sempre simples, beleza, mas não existe uma garantia de que tudo vai funcionar com os dois bancos.

**Comment by rodolfobandeira** [comment]
Eh.. tem q rolar um padrao de query.. nada de coisa maluca.. :+1:

**Comment by mathiasgrimm** [comment]
blz fechou!

as migrations e seeds pra mysql j'a estao criados
