### ISSUE TITLE
TDD

### ISSUE THREAD

**Issue by edertaveira** [phpEmpregos/phpEmpregos.com#54]
O que acham de utilizarmos TDD neste projeto?

**Comment by mathiasgrimm** [comment]
Com certeza.
Temos que ter testes para as principais funcionalidades.
Nao seria 100% mas seria com testes

**Comment by mathiasgrimm** [comment]
cada pessoa que desenvolver/alterar uma funcionalidade vai ter q criar/atualizar os testes .

Podem ser pessoas diferentes fazendo isso tambem, mas temos q testar bem, isso vai facilitar qualquer tipo de mudan'cas no projeto

**Comment by leocavalcante** [comment]
Só lembrando que criar uma funcionalidade e o teste depois, não é TDD. A ideia do TDD é você desenvolver com base nos testes, TDD não é só o fato de ter testes, é toda uma metodologia.

**Comment by mathiasgrimm** [comment]
ppr isso falei q n seria 100 tdd mas teriam testes
