### ISSUE TITLE
Projeto Julia!

### ISSUE THREAD

**Issue by mathiasgrimm** [phpEmpregos/phpEmpregos.com#55]
Minha primeira filha, Julia, vai nascer a qualquer momento. Supostamente é dia 18 de Março mas pode ser a qualquer momento então talvez eu fique meio ausente por alguns dias mas o projeto não para!

**Comment by dunice** [comment]
Parabéns, @mathiasgrimm! Muita saúde e paz a ela!

**Comment by leocavalcante** [comment]
Parabéns cara, tudo de bom, muita saúde!

**Comment by mathiasgrimm** [comment]
vlw pessoal!

**Comment by miltonviziak** [comment]
parabens ae, felicidades mathias

**Comment by vanildosouto** [comment]
Parabéns!! Sei que todo mundo fala isso, mas aproveita pra dormir! rsrs. Tenho uma garoto de 2 anos, lindo, vive correndo pela casa. Toda a alegria que essa criança traz, compensa o cansaço. Parabéns novamente.

**Comment by mathiasgrimm** [comment]
Nasceu!

nasceu segunda dia 16 de marco de 2015 as 10:03 aki dublin irlanda! ta td bem gracas ao nosso bom Deus!

**Comment by rodolfobandeira** [comment]
@mathiasgrimm Parabens!

**Comment by Jessica7** [comment]
Graças a Deus!

**Comment by mathiasgrimm** [comment]
Valeu pessoal!
